svcstat: Refactoring tabs vs spaces

diff --git a/terminal/scripts/svcstat b/terminal/scripts/svcstat
--- a/terminal/scripts/svcstat
+++ b/terminal/scripts/svcstat
@@ -17,67 +17,67 @@ ONELINE=0
 
 # Parsing command line args
 case "$1" in
-	-stop)
-		RUN_MODE="stop"
-		;;
-	--oneline | -o)
-		ONELINE=1
-		;;
+  -stop)
+    RUN_MODE="stop"
+    ;;
+  --oneline | -o)
+    ONELINE=1
+    ;;
 esac
 
 if [ "$RUN_MODE" = "stat" ];
 then
-	for svc in "${services[@]}"
-	do
-		cmd="systemctl --no-pager status $svc"
-		result=`$cmd 2>/dev/null`
-		readarray -t lines <<<"$result"
+  for svc in "${services[@]}"
+  do
+    cmd="systemctl --no-pager status $svc"
+    result=`$cmd 2>/dev/null`
+    readarray -t lines <<<"$result"
 
-		# check if service does not exist
-		if [ ${#lines[@]} -eq 1 ];
-		then
-			echo -e "${RED}x${RCOL} Service ${svc} not found"
-			continue
-		fi
+    # check if service does not exist
+    if [ ${#lines[@]} -eq 1 ];
+    then
+      echo -e "${RED}x${RCOL} Service ${svc} not found"
+      continue
+    fi
 
-		activeline="${lines[2]}"
-		isactive=${activeline:13:6}
-		if [ "$isactive" = "active" ]
-		then
-			if [[ $ONELINE == 1 ]]
-			then
-				echo -e "${GREEN}${lines[0]} - Active${RCOL}"
-			else
-				echo -e "${GREEN}${lines[0]}${RCOL}"
-				echo "${lines[2]}"
-			fi
-		else
-			isinactive=${activeline:13:8}
-			if [ "$isinactive" = "inactive" ]
-			then
-				if [[ $ONELINE == 1 ]]
-				then
-					echo "${lines[0]} - Inactive"
-				else
-					echo "${lines[0]}"
-					echo "${lines[2]}"
-				fi
-			fi
-		fi
-	done
+    activeline="${lines[2]}"
+    isactive=${activeline:13:6}
+    if [ "$isactive" = "active" ]
+    then
+      if [[ $ONELINE == 1 ]]
+      then
+        echo -e "${GREEN}${lines[0]} - Active${RCOL}"
+      else
+        echo -e "${GREEN}${lines[0]}${RCOL}"
+        echo "${lines[2]}"
+      fi
+    else
+      isinactive=${activeline:13:8}
+      if [ "$isinactive" = "inactive" ]
+      then
+        if [[ $ONELINE == 1 ]]
+        then
+          echo "${lines[0]} - Inactive"
+        else
+          echo "${lines[0]}"
+          echo "${lines[2]}"
+        fi
+      fi
+    fi
+  done
 elif [ "$RUN_MODE" = "stop" ];
 then
-	# Check if running as root
-	if [ "$EUID" -ne 0 ]
-	then
-		echo "Stopping services require root privileges."
-		exit 1
-	fi
+  # Check if running as root
+  if [ "$EUID" -ne 0 ]
+  then
+    echo "Stopping services require root privileges."
+    exit 1
+  fi
 
-	for svc in "${services[@]}"
-	do
-		eval "systemctl stop $svc"
-	done
+  for svc in "${services[@]}"
+  do
+    eval "systemctl stop $svc"
+  done
 fi
 
 exit 0
